### ISSUE TITLE
Create Professor View

### ISSUE THREAD

**Issue by cannotparse** [inspectorG4dget/AnonymousFeedback#11]
The Professor view allows you to:
* Add TA's
* Add Course's
* Add Sections
* View Feedback
* * Based on TA
* * Based on Section 
* * Based on Course

**Comment by inspectorG4dget** [comment]
For now, I'd leave this to our DB scripts to pre-populate with Course - Section - Professor - TA data. This way, it'll look more like the finished thing, when this system is integrated into uOttawa's ecosystem.
