### ISSUE TITLE
Create Section

### ISSUE THREAD

**Issue by cannotparse** [inspectorG4dget/AnonymousFeedback#15]
Within the professor view, create section feature

sub of #11

**Comment by inspectorG4dget** [comment]
Required JSON:
{courseCode: "ITI1120",
 sectionCode: "T1",
 year: 2016,
 semester: 2,
 weekday: 1,
 startTime: "11:30",
 endTime: "14:30"
}

**Comment by cannotparse** [comment]
Required JSON:
{courseCode: "ITI1120",
sectionCode: "T1",
startTime: "11:30",
endTime: "14:30",
semesterCode:"2"
}

**Comment by inspectorG4dget** [comment]
Required JSON:
{courseCode: "ITI1120",
sectionCode: "T1",
year: 2016,
semester: 2,
weekday: 1,
startTime: "11:30",
endTime: "14:30"
}
