### ISSUE TITLE
Only show Sections with an assigned TA

### ISSUE THREAD

**Issue by cannotparse** [inspectorG4dget/AnonymousFeedback#16]
Currently, the app will allow feedback on sections without verifying if they have a TA

Would recommend doing #8 and #9 first since they will require revising the Schema

**Comment by inspectorG4dget** [comment]
The app should assume that only sections with TAs will be available. Again, this is to be integrated with uO's databases, which will have this information. TUT/DGD sections can't not have a TA

**Comment by cannotparse** [comment]
New DB Schema and feedback submission system fixes this
