### ISSUE TITLE
Assign TA to section

### ISSUE THREAD

**Issue by cannotparse** [inspectorG4dget/AnonymousFeedback#19]
sub of #11 

Within the professor view, create feature to assign TA's to sections based on Course code and Section

**Comment by inspectorG4dget** [comment]
Required JSON:
{taID: 1,
 courseCode: "ITI1120",
 sectionCode: "T1"
}

**Comment by cannotparse** [comment]
For the getTAs handler, please output the TAs in the following output
```javascript
{
results : [
    ["1","Ashwin Pancakes"],
    ["2","Remi gel"]
]
}
```
