### ISSUE TITLE
Page flow

### ISSUE THREAD

**Issue by cannotparse** [inspectorG4dget/AnonymousFeedback#2]
How will we model the user interaction from / and inwards?

**Comment by inspectorG4dget** [comment]
When the user hits /, they are asked if they are a student or a professor
If they are a student, send them to student.html (where they can enter TA feedback)
If they are a professor, send them to professor.html.

professor.html asks for a professor ID (say, employee number), the course code for the course they teach, and the section code for which they would like to add a TA. Multiple text boxes are present, so the professor can add multiple TA names to that section of that course. We will therefore need a new database table containing professorID, courseCode, sectionCode
