### ISSUE TITLE
Make submitFeedback endpoint work with updated view

### ISSUE THREAD

**Issue by cannotparse** [inspectorG4dget/AnonymousFeedback#25]
The updated view now sends a form with data for multiple TAs if multiple are associated with a class.

Please describe the input JSON format you will be expecting.

**Comment by inspectorG4dget** [comment]
Pending #24 
Expected JSON:

'[{"student": 1234567, 
   "taID": "1", 
   "course": "ITI1120", 
   "section": "T1", 
   "currYear": 2016, 
   "semester": 1, 
   "q1": 5, 
   "q2": 5, 
   "q3": 5, 
   "feedback": "woohoo"}]'

**Comment by cannotparse** [comment]
I'm going to adjust it to the following for the time being. 
```Javascipt
{
    "student": 1234567, 
    "course": "ITI1120", 
    "section": "T1", 
    "currYear": 2016,    
    "semester": 1,  
    "feedback" : [ 
        {
            "taID": "1", 
            "q1": 5, 
            "q2": 5, 
            "q3": 5, 
            "feedback": "woohoo"
      },
        {
            "taID": "2", 
            "q1": 2, 
            "q2": 2, 
            "q3": 3, 
            "feedback": "choochoo"
      }
      ]
}
```
