### ISSUE TITLE
API or Client js

### ISSUE THREAD

**Issue by cannotparse** [inspectorG4dget/AnonymousFeedback#3]
Should we have a step by step process where the user sends an input, the server responds with a new list OR should we populate an HTML dropdown only?

**Comment by cannotparse** [comment]
I'm opting for a light weight API:
Student hits / -> Server provides a page with a dropdown of courses
Student Select Course from dropdown (triggering a post request) -> Server responds with a JSON of sections which the client js updates the page
Student Select Section -> UI updates to reveal feedback fields
Student fills the forms and sends it (post request) -> Server affirms the receipt. 
Done

**Comment by inspectorG4dget** [comment]
That works
