### ISSUE TITLE
Application fails to display section and location data for certain classes

### ISSUE THREAD

**Issue by scriptbae** [inspectorG4dget/AnonymousFeedback#33]
Using the current master:HEAD (5e692f20a11302b906aceb5d1b61d6f5b48758d7) and the included bootstrapping file (`db_setup.sql`) and testing data (`db_test_data.sql`), the application fails to load time and section information for classes `ITI1120` and `CEG2136`. This results in no feedback form being displayed for either of these courses.

The cause of this issue requires diagnosis.

This problem does not affect `ITI1121` from the testing data.

**Comment by cannotparse** [comment]
Because the dates for those sections are set to 2016. Check the implementation of 
`def getYearSemester(year=None, month=None):` from `backend.py`
This is the code I fixed and posted in slack.
```SLQ
INSERT INTO teaches(taID, course, section, currYear, semester) VALUES
('1', 'ITI1120', 'T1', '2016', '1'),
('1', 'CEG2136', 'T1', '2016', '1'),
('4', 'CEG2136', 'T1', '2016', '1'),
('2', 'ITI1120', 'T2', '2016', '1'),
('1', 'ITI1121', 'T2', '2017', '2'),
('3', 'ITI1121', 'T1', '2017', '2');
```

**Comment by scriptbae** [comment]
Tentatively resolved.
