### ISSUE TITLE
pg8000.ProgrammingError raised when adding a course

### ISSUE THREAD

**Issue by scriptbae** [inspectorG4dget/AnonymousFeedback#36]
As a professor, adding a section, a `pg8000.ProgrammingError` (normally caused by bad syntax) is raised when adding a course. The origin of this error is an invocation of `cursor.execute()` at `dbhandler.py:89` inside `createCourse()`:

```
t.execute("""INSERT INTO course(code) VALUES (%s)""", (courseCode,))
```

**Comment by cannotparse** [comment]
If an error have been thrown from a prior test, then all executions will block. When executing without error, this runs fine. Closing.
