### ISSUE TITLE
pg8000.ProgrammingError raised under special circumstances when selecting "Add section"

### ISSUE THREAD

**Issue by scriptbae** [inspectorG4dget/AnonymousFeedback#37]
_Note: this appears unrelated to #36._

If a course code is entered under _Add course_ and _Add section_ is selected from the dropdown, a `pg8000.ProgrammingError` is raised. The source of this issue is `dbhandler.py:40`, inside `getCourses()`:

```
t.execute("""SELECT * FROM course""")
```

**Comment by cannotparse** [comment]
Could not recreate issue. Same deal as before, once pg8000 get an error, you need to finish the transaction block. 
Will need to later implement error handling. For now, lets avoid all errors than fix this.
