### ISSUE TITLE
Fix handling of input on /submitFeedBack

### ISSUE THREAD

**Issue by scriptbae** [inspectorG4dget/AnonymousFeedback#44]
Currently, the `/submitFeedback` endpoint raises a 500 error on POST because of a type conflict on the `pg8000` layer. This restricts testing related to #29 and should be resolved immediately as it impairs the progress of #29.

**Comment by scriptbae** [comment]
Fix implemented, will be shipped in next PR. My bad for not implementing a separate feature branch for this.

**Comment by cannotparse** [comment]
Issue was not mentioned in commit message 👎  
:(

**Comment by verandaguy** [comment]
@NuclearBanane it was mentioned in comments following up on the PR... and also in the message for 753ee58
