### ISSUE TITLE
Refactor getCourseFeedbacks database API function to circumvent unpacking error

### ISSUE THREAD

**Issue by scriptbae** [inspectorG4dget/AnonymousFeedback#46]
There's an immediately relevant issue in `dbhandler.getCourseFeedbacks` where a `for` loop attempts to unpack an 8-element list into 10 elements.

The problematic elements are those representing the start and end times of a section.

Upon inspection, these two problem values may not be consequential in the Professor view.

RFC: should these two values be preserved (which would require changes to the DB query in this function)?

**Comment by cannotparse** [comment]
Which two values?

**Comment by scriptbae** [comment]
@NuclearBanane the loop attempts to unpack `startTime` and `endTime`, but the SQL query which retrieves the data from the DB doesn't fetch those columns.

**Comment by scriptbae** [comment]
Function will be refactored to exclude the `startTime` and `endTime` fields in the response payload.
