### ISSUE TITLE
Change Text on Range Questions

### ISSUE THREAD

**Issue by inspectorG4dget** [inspectorG4dget/AnonymousFeedback#69]
There are currently three range questions, answered on a 1-10 range.
These questions currently have generic text in them. The text needs to be changed as follows:

1. I find the TA well prepared for class
1. I think the TA conveys the subject matter effectively
1. I find that the TA, as a TA is...

**Comment by scriptbae** [comment]
@inspectorG4dget what's meant by `question 1`, `question 4`, and `question 9`? (They're the squares of the actual numbers by all appearances...)

**Comment by inspectorG4dget** [comment]
Sorry, that's from Dr. Viktor's email to me, and does not belong here. I've edited the issue to reflect this

**Comment by scriptbae** [comment]
Closed by 1127565.
