### ISSUE TITLE
Change Tick-Text on Range Questions

### ISSUE THREAD

**Issue by inspectorG4dget** [inspectorG4dget/AnonymousFeedback#71]
Change the text on the ticks for the range questions to:

-2: Strongly disagree
-1: Somewhat disagree
 0: Neutral
+1: Somewhat agree
+2: Strongly agree

**Comment by scriptbae** [comment]
Suggest having 0 as "Neither agree nor disagree;" this is what most of these kinds of questions in the wild use.

**Comment by inspectorG4dget** [comment]
Agreed

**Comment by scriptbae** [comment]
Closed by 1127565.
