### ISSUE TITLE
Aggregate Data in Professor View of TA Feedback

### ISSUE THREAD

**Issue by inspectorG4dget** [inspectorG4dget/AnonymousFeedback#73]
When a professor requests to view the feedback for a specific TA, we currently show mean and stdev of the values of the range questions, along with the number of feedback records in total.
However, the values of the range questions have specific meaning (as explained in issue #71).
Therefore, we should display that meaningful text in the range aggregation as well.

Since we have the mean and the stdev, we can use D3 (or similar) to plot a gaussian distribution with the range ticks on the x axis and the range labels on the x-axis-tick-labels.

We should also draw a vertical line at the mean, with an additional label at the x axis, mentioning its value

**Comment by scriptbae** [comment]
Iceboxing until a future release.
