### ISSUE TITLE
Add TA Rank to Professor View

### ISSUE THREAD

**Issue by inspectorG4dget** [inspectorG4dget/AnonymousFeedback#74]
In the Professor view, we should show how well a queried TA stacks up against the other TAs.

Let us suppose the following about the current semester, for the sake of discussion:
The professor has asked about the course ITI1120
ITI1120 has 3 sections that require TAs
ITI 1120 has a total of 5 TAs to run these 3 sections (maybe some sections have a LAB and a DGD)
There are a total of 100 TAs in uOttawa
Each TA has 20 reviews
All reviews are legitimate (i.e. there's no fake student numbers, etc)

When the professor queries a TA's information, the professor currently sees the following:
1. Aggregates (mean, stdev) of the TA's performance on range questions, as well as the number of feedbacks
2. The raw data for each range question and free-form feedback text.

In addition to what we already display about a TA, we should display the following two graphs:

**Graph 1**:
1. Compute the mean and stdev of the range questions of the other 4 ITI1120 TAs
1. Render a Gaussian distribution from those parameters and plot it in orange color
1. Draw a perpendicular line, intersecting the x axis at the mean
1. Label the mean value on the x axis
1. Compute the mean and stdev of the range questions for the queried TA
1. Render  a Gaussian distribution from those parameters and plot it in blue color
1. Draw a perpendicular line, intersecting the x axis at the mean
1. Label the mean value on the x axis

**Graph 2**:
1. Compute the mean and stdev of the range questions of the other 99 uOttawa TAs
1. Render a Gaussian distribution from those parameters and plot it in red color
1. Draw a perpendicular line, intersecting the x axis at the mean
1. Label the mean value on the x axis
1. Compute the mean and stdev of the range questions for the queried TA
1. Render  a Gaussian distribution from those parameters and plot it in blue color
1. Draw a perpendicular line, intersecting the x axis at the mean
1. Label the mean value on the x axis

**Comment by scriptbae** [comment]
Putting this on ice pending a future release. (Iceboxed issues are closed with the `icebox` tag, to be resuscitated later as appropriate. This is to unclutter the active issue queue).
