### ISSUE TITLE
Need to display Section ID 

### ISSUE THREAD

**Issue by cannotparse** [inspectorG4dget/AnonymousFeedback#8]
Related to #5 
The section ID, such as ITI1120B01 where B01 is the section ID needs to be returned. 

This means its needs to be added as a field in the DB.

**Comment by inspectorG4dget** [comment]
Whose view is this in? There is a need to display this to a professor; there is no immediate need to display this to a student

**Comment by cannotparse** [comment]
No longer considered part of MVP nor #5 
Added to refined demo

**Comment by cannotparse** [comment]
Fixed with new Feedback submission system and schema
